package br.com.barrildobrado.chavesdebolso.model;

import br.com.barrildobrado.chavesdebolso.R;
import br.com.barrildobrado.chavesdebolso.activity.HomeActivity;

public class ScriptsSQL {
    /**
     * Scripts de criação
     */
    public static String CREATE_TABLE_PERSONAGEM = "CREATE TABLE IF NOT EXISTS PERSONAGEM (_id INTEGER PRIMARY KEY NOT NULL, nomePersonagem VARCHAR (255) );";
    public static String CREATE_TABLE_FRASE = "CREATE TABLE IF NOT EXISTS FRASE ( _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, idIcone INTEGER, idBackground INTEGER, idMedia INTEGER, idStrFrase INTEGER, idAssinatura INTEGER, idPersonagem INTEGER NOT NULL CONSTRAINT FK_FRASE_PERSONAGEM REFERENCES PERSONAGEM (_id) );";

    /**
     * Scripts de drop
     */
    public static String DROP_TABLE_PERSONAGEM = "DROP TABLE IF EXISTS PERSONAGEM";
    public static String DROP_TABLE_FRASE = "DROP TABLE IF EXISTS FRASE";

    /**
     * Scripts de insert personagem
     */
    public static String INSERT_INTO_PERSONAGEM_1 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('BARRIGA')";
    public static String INSERT_INTO_PERSONAGEM_2 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('CHAVES')";
    public static String INSERT_INTO_PERSONAGEM_3 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('CHIQUINHA')";
    public static String INSERT_INTO_PERSONAGEM_4 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('CLOTILDES')";
    public static String INSERT_INTO_PERSONAGEM_5 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('FLORINDA')";
    public static String INSERT_INTO_PERSONAGEM_6 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('GIRAFALES')";
    public static String INSERT_INTO_PERSONAGEM_7 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('KIKO')";
    public static String INSERT_INTO_PERSONAGEM_8 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('MADRUGA')";
    public static String INSERT_INTO_PERSONAGEM_9 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('NHONHO')";
    public static String INSERT_INTO_PERSONAGEM_10 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('GODINEZ')";
    public static String INSERT_INTO_PERSONAGEM_11 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('POPIS')";
    public static String INSERT_INTO_PERSONAGEM_12 = "INSERT OR REPLACE INTO PERSONAGEM (nomePersonagem) VALUES('ESPECIAL')";

    /**
     * Scripts de insert frases
     */
    public static String INSERT_INTO_FRASE_1 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_barriga +", "+ R.drawable.bg_barriga +", "+ R.raw.barriga_pague_aluguel +", "+ R.string.barriga_pague_aluguel +", "+ R.string.assinatura_barriga +", "+ HomeActivity.Personagem.BARRIGA.getValue() +")";
    public static String INSERT_INTO_FRASE_2 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_n_se_irrite +", "+ R.string.chaves_mas_nao_se_irrite +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_3 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_melhor_ver_pele +", "+ R.string.chaves_melhor_ver_pele +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_4 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_da_zero +", "+ R.string.chaves_da_zero +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_5 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_gato_um_olho +", "+ R.string.chaves_gato_um_olho +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_6 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_outro_gato +", "+ R.string.chaves_outro_gato +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_7 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_amar_inimigos +", "+ R.string.chaves_amar_inimigos +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_8 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_bebercio +", "+ R.string.chaves_bebercio +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_9 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_isso_isso_isso +", "+ R.string.chaves_isso_isso_isso +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_10 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_ja_chegou_disco_voador +", "+ R.string.chaves_ja_chegou_disco_voador +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_11 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_me_escapuliu +", "+ R.string.chaves_me_escapuliu +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_12 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_morrer_perder_vida +", "+ R.string.chaves_morrer_perder_vida +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_13 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_nao_tem_biscoito +", "+ R.string.chaves_nao_tem_biscoito +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_14 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_paciencia_comigo +", "+ R.string.chaves_paciencia_comigo +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_15 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_quanto_custa +", "+ R.string.chaves_quanto_custa +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_16 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_refrescos +", "+ R.string.chaves_refrescos +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_17 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chaves +", "+ R.drawable.bg_chaves +", "+ R.raw.chaves_sem_querer_querendo +", "+ R.string.chaves_sem_querer_querendo +", "+ R.string.assinatura_chaves +", "+ HomeActivity.Personagem.CHAVES.getValue() +")";
    public static String INSERT_INTO_FRASE_18 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_kiko +", "+ R.drawable.bg_kiko +", "+ R.raw.kiko_nao_vai_cara +", "+ R.string.kiko_nao_vai_cara +", "+ R.string.assinatura_kiko +", "+ HomeActivity.Personagem.KIKO.getValue() +")";
    public static String INSERT_INTO_FRASE_19 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_kiko +", "+ R.drawable.bg_kiko +", "+ R.raw.kiko_gato_aniversario +", "+ R.string.kiko_gato_aniversario +", "+ R.string.assinatura_kiko +", "+ HomeActivity.Personagem.KIKO.getValue() +")";
    public static String INSERT_INTO_FRASE_20 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_kiko +", "+ R.drawable.bg_kiko +", "+ R.raw.kiko_gentalha +", "+ R.string.kiko_gentalha +", "+ R.string.assinatura_kiko +", "+ HomeActivity.Personagem.KIKO.getValue() +")";
    public static String INSERT_INTO_FRASE_21 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_kiko +", "+ R.drawable.bg_kiko +", "+ R.raw.kiko_mamae +", "+ R.string.kiko_mamae +", "+ R.string.assinatura_kiko +", "+ HomeActivity.Personagem.KIKO.getValue() +")";
    public static String INSERT_INTO_FRASE_22 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_kiko +", "+ R.drawable.bg_kiko +", "+ R.raw.kiko_cale_se +", "+ R.string.kiko_cale_se +", "+ R.string.assinatura_kiko +", "+ HomeActivity.Personagem.KIKO.getValue() +")";
    public static String INSERT_INTO_FRASE_23 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_kiko +", "+ R.drawable.bg_kiko +", "+ R.raw.kiko_nao_seja_mau_sim +", "+ R.string.kiko_nao_seja_mau_sim +", "+ R.string.assinatura_kiko +", "+ HomeActivity.Personagem.KIKO.getValue() +")";
    public static String INSERT_INTO_FRASE_24 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_trabalhar +", "+ R.string.madruga_ruim_ter_que_trabalhar +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_25 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_chapeus_sapatos +", "+ R.string.madruga_chapeus_sapatos +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_26 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_chaves_de_novo +", "+ R.string.madruga_chaves_de_novo +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_27 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_higienicos_churros +", "+ R.string.madruga_higienicos_churros +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_28 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_nao_te_dou_outra +", "+ R.string.madruga_nao_te_dou_outra +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_29 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_olha_churros +", "+ R.string.madruga_olha_churros +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_30 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_que_foi_que_ha +", "+ R.string.madruga_que_foi_que_ha +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_31 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_velha_ridicula +", "+ R.string.madruga_velha_ridicula +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_32 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_madruga +", "+ R.drawable.bg_madruga +", "+ R.raw.madruga_vinganca_nunca_plena +", "+ R.string.madruga_vinganca_nunca_plena +", "+ R.string.assinatura_madruga +", "+ HomeActivity.Personagem.MADRUGA.getValue() +")";
    public static String INSERT_INTO_FRASE_33 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_nhonho +", "+ R.drawable.bg_nhonho +", "+ R.raw.nhonho_nao_almocei +", "+ R.string.nhonho_nao_almocei_festa +", "+ R.string.assinatura_nhonho +", "+ HomeActivity.Personagem.NHONHO.getValue() +")";
    public static String INSERT_INTO_FRASE_34 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_nhonho +", "+ R.drawable.bg_nhonho +", "+ R.raw.nhonho_olha_ele +", "+ R.string.nhonho_olha_ele +", "+ R.string.assinatura_nhonho +", "+ HomeActivity.Personagem.NHONHO.getValue() +")";
    public static String INSERT_INTO_FRASE_35 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_choro +", "+ R.string.chiquinha_choro +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_36 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_jeca_valente +", "+ R.string.chiquinha_jeca_valente +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_37 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_conciencia_limpa +", "+ R.string.chiquinha_consciencia_limpa +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_38 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_papaizinho_lindo +", "+ R.string.chiquinha_papaizinho_lindo +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_39 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_pois_e +", "+ R.string.chiquinha_pois_e +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_40 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_subir_cadeira +", "+ R.string.chiquinha_subir_cadeira +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_41 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_chiquinha +", "+ R.drawable.bg_chiquinha +", "+ R.raw.chiquinha_tem_de_burro +", "+ R.string.chiquinha_tem_de_burro +", "+ R.string.assinatura_chiquinha +", "+ HomeActivity.Personagem.CHIQUINHA.getValue() +")";
    public static String INSERT_INTO_FRASE_42 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_clotildes +", "+ R.drawable.bg_clotildes +", "+ R.raw.clotilde_ai_minha_nossa +", "+ R.string.clotilde_ai_minha_nossa +", "+ R.string.assinatura_clotildes +", "+ HomeActivity.Personagem.CLOTILDES.getValue() +")";
    public static String INSERT_INTO_FRASE_43 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_clotildes +", "+ R.drawable.bg_clotildes +", "+ R.raw.clotilde_eh_vc_satanas +", "+ R.string.clotilde_eh_vc_satanas +", "+ R.string.assinatura_clotildes +", "+ HomeActivity.Personagem.CLOTILDES.getValue() +")";
    public static String INSERT_INTO_FRASE_44 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_clotildes +", "+ R.drawable.bg_clotildes +", "+ R.raw.clotilde_quem_eh_bruxa +", "+ R.string.clotilde_quem_eh_bruxa +", "+ R.string.assinatura_clotildes +", "+ HomeActivity.Personagem.CLOTILDES.getValue() +")";
    public static String INSERT_INTO_FRASE_45 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_clotildes +", "+ R.drawable.bg_clotildes +", "+ R.raw.clotilde_porque_bruxa +", "+ R.string.clotilde_porque_bruxa +", "+ R.string.assinatura_clotildes +", "+ HomeActivity.Personagem.CLOTILDES.getValue() +")";
    public static String INSERT_INTO_FRASE_46 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_clotildes +", "+ R.drawable.bg_clotildes +", "+ R.raw.clotilde_venha_satanas +", "+ R.string.clotilde_venha_satanas +", "+ R.string.assinatura_clotildes +", "+ HomeActivity.Personagem.CLOTILDES.getValue() +")";
    public static String INSERT_INTO_FRASE_47 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_bruxa_madruga_moca_bonita +", "+ R.string.especial_bruxa_madruga_moca_bonita +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_48 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_tatata_quem_eh +", "+ R.string.especial_tatata_quem_eh +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_49 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_dona_massacote +", "+ R.string.especial_dona_massacote +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_50 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_bruxa_madruga_conto_bruxas +", "+ R.string.especial_bruxa_madruga_conto_bruxas +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_51 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_dor_coracao +", "+ R.string.especial_dor_coracao +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_52 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_linda +", "+ R.string.especial_linda +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_53 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_especial +", "+ R.drawable.bg_especial +", "+ R.raw.especial_refresco_abacaxi +", "+ R.string.especial_refresco_abacaxi +", "+ R.string.assinatura_especial +", "+ HomeActivity.Personagem.ESPECIAL.getValue() +")";
    public static String INSERT_INTO_FRASE_54 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_florinda +", "+ R.drawable.bg_florinda +", "+ R.raw.florinda_estou_falando +", "+ R.string.florinda_estou_falando +", "+ R.string.assinatura_florinda +", "+ HomeActivity.Personagem.FLORINDA.getValue() +")";
    public static String INSERT_INTO_FRASE_55 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_florinda +", "+ R.drawable.bg_florinda +", "+ R.raw.florinda_gentalha +", "+ R.string.florinda_gentalha +", "+ R.string.assinatura_florinda +", "+ HomeActivity.Personagem.FLORINDA.getValue() +")";
    public static String INSERT_INTO_FRASE_56 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_florinda +", "+ R.drawable.bg_florinda +", "+ R.raw.florinda_proxima_vez +", "+ R.string.florinda_proxima_vez +", "+ R.string.assinatura_florinda +", "+ HomeActivity.Personagem.FLORINDA.getValue() +")";
    public static String INSERT_INTO_FRASE_57 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_girafales +", "+ R.drawable.bg_girafales +", "+ R.raw.girafales_tatatatatatata +", "+ R.string.girafales_tatatatatatata +", "+ R.string.assinatura_girafales +", "+ HomeActivity.Personagem.GIRAFALES.getValue() +")";
    public static String INSERT_INTO_FRASE_58 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_girafales +", "+ R.drawable.bg_girafales +", "+ R.raw.girafales_causa_motivo_razao_circunstancia +", "+ R.string.girafales_causa_motivo_razao_circunstancia +", "+ R.string.assinatura_girafales +", "+ HomeActivity.Personagem.GIRAFALES.getValue() +")";
    public static String INSERT_INTO_FRASE_59 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_girafales +", "+ R.drawable.bg_girafales +", "+ R.raw.girafales_come_com_rabo +", "+ R.string.girafales_come_com_rabo +", "+ R.string.assinatura_girafales +", "+ HomeActivity.Personagem.GIRAFALES.getValue() +")";
    public static String INSERT_INTO_FRASE_60 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_godinez +", "+ R.drawable.bg_godinez +", "+ R.raw.godinez_pista +", "+ R.string.godinez_pista +", "+ R.string.assinatura_godinez +", "+ HomeActivity.Personagem.GODINEZ.getValue() +")";
    public static String INSERT_INTO_FRASE_61 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_godinez +", "+ R.drawable.bg_godinez +", "+ R.raw.godinez_nao_fui_eu +", "+ R.string.godinez_nao_fui_eu +", "+ R.string.assinatura_godinez +", "+ HomeActivity.Personagem.GODINEZ.getValue() +")";
    public static String INSERT_INTO_FRASE_62 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_godinez +", "+ R.drawable.bg_godinez +", "+ R.raw.godinez_assobio +", "+ R.string.godinez_assobio +", "+ R.string.assinatura_godinez +", "+ HomeActivity.Personagem.GODINEZ.getValue() +")";
    public static String INSERT_INTO_FRASE_63 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_godinez +", "+ R.drawable.bg_godinez +", "+ R.raw.godinez_colares_perolas +", "+ R.string.godinez_colares_perolas +", "+ R.string.assinatura_godinez +", "+ HomeActivity.Personagem.GODINEZ.getValue() +")";
    public static String INSERT_INTO_FRASE_64 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_godinez +", "+ R.drawable.bg_godinez +", "+ R.raw.godinez_confirmando +", "+ R.string.godinez_confirmando +", "+ R.string.assinatura_godinez +", "+ HomeActivity.Personagem.GODINEZ.getValue() +")";
    public static String INSERT_INTO_FRASE_65 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_godinez +", "+ R.drawable.bg_godinez +", "+ R.raw.godinez_verdadeiro_falso +", "+ R.string.godinez_verdadeiro_falso +", "+ R.string.assinatura_godinez +", "+ HomeActivity.Personagem.GODINEZ.getValue() +")";
    public static String INSERT_INTO_FRASE_66 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_popis +", "+ R.drawable.bg_popis +", "+ R.raw.popis_conta_tudo_mae +", "+ R.string.popis_conta_tudo_mae +", "+ R.string.assinatura_popis +", "+ HomeActivity.Personagem.POPIS.getValue() +")";
    public static String INSERT_INTO_FRASE_67 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_popis +", "+ R.drawable.bg_popis +", "+ R.raw.popis_cabral_compositor +", "+ R.string.popis_cabral_compositor +", "+ R.string.assinatura_popis +", "+ HomeActivity.Personagem.POPIS.getValue() +")";
    public static String INSERT_INTO_FRASE_68 = "INSERT OR REPLACE INTO FRASE (idIcone, idBackground, idMedia, idStrFrase, idAssinatura, idPersonagem) VALUES("+ R.drawable.icn_popis +", "+ R.drawable.bg_popis +", "+ R.raw.popis_quantos_centimetros_metro +", "+ R.string.popis_quantos_centimetros_metro +", "+ R.string.assinatura_popis +", "+ HomeActivity.Personagem.POPIS.getValue() +")";

}
